title    : Test Definition Schema
type     : object
required :
  - name
  - tests
  - command

properties :
  name    :
    required : 1
    type     : string
  tests   :
    required : 1
    type     : integer
    minimum  : 1
  command :
    required : 1
    type     : array
    items    :
      type : string
  branch  :
    type     : string

patternProperties :
  \d+ :
    type                 : object
    additionalProperties : 0
    properties           :

      command :
        type  : array
        items :
          type : string

      branch :
        type : string

      diff    :
        type              : object
        patternProperties :
          .* :
            type    : string
            pattern : ^[AMD]$

      files   :
        type              : object
        patternProperties :
          .* :
            type       : object
            properties :
              exists  :
                type : {enum : [0, 1]}
              content :
                type : string
