#!/usr/bin/perl
use strict;
use warnings;
use Cwd            qw(abs_path);
use File::Basename qw(dirname);
use File::Path     qw(make_path remove_tree);
use File::Slurp    qw(slurp);
use Getopt::Long;
use YAML           qw(LoadFile);
BEGIN { push @INC, dirname $0 }
use Test101::Test;


use constant OPTIONS => qw(config schema cd results);

my %options;
GetOptions(\%options, map { "$_=s" } OPTIONS);

for (OPTIONS)
{
    die "Missing required option: $_" if not defined $options{$_};
    make_path($options{$_})           if not -e      $options{$_};
    $options{$_} = abs_path $options{$_} or die "Invalid path: $_ ($!)";
}


Test101::Test->new(
    %options,
    config => LoadFile($options{config}),
    schema => LoadFile($options{schema}),
)->test;
