#!/usr/bin/perl
use strict;
use warnings;
use Cwd            qw(abs_path);
use File::Path     qw(make_path);
use Getopt::Long;
use YAML           qw(LoadFile);
use Test101::Test;


use constant OPTIONS => qw(config schema cd output);

my %options;
GetOptions(\%options, map { "$_=s" } OPTIONS);

for (OPTIONS)
{
    die "Missing required option: $_\n" if not defined $options{$_};
    make_path($options{$_})             if not -e      $options{$_};
    $options{$_} = abs_path $options{$_} or die "Invalid path: $_ ($!)\n";
}


Test101::Test->new(
    %options,
    diffs  => "$options{output}/101diffs",
    config => LoadFile($options{config}),
    schema => LoadFile($options{schema}),
)->test;
