name    : matches101meta
tests   : 5
command : make -s test-matches101meta.debug

# Empty matches with no rules.
1 :
  diff   :
    101repo/README.md              : A
    101web/data/dumps/rules.json   : A
    101web/data/dumps/matches.json : A
  files  : &emptymatches
    101web/data/dumps/matches.json :
      json : |
        {
            "failures" : {},
            "matches"  : [],
            "rules"    : []
        }

# Same thing again to make sure that no superfluous diff is generated.
2 :
  branch : matches101meta1
  diff   : {}
  files  : *emptymatches

# Now with rules and files to match over.
# There's no rules for C here, so stuff in Contributions/C shouldn't match.
3 :
  indiff :
    101web/data/dumps/rules.json                                              : M
    101web/data/dumps/matches.json                                            : M
    101web/data/resources/Contributions/C/main.c                              : ~
    101web/data/resources/Contributions/C/Header.h                            : ~
    101web/data/resources/Contributions/CPlusPlus/main.cpp.matches.json       : A
    101web/data/resources/Contributions/CPlusPlus/Header.hpp.matches.json     : A
    101web/data/resources/Contributions/Java/Main.java.matches.json           : A
    101web/data/resources/Contributions/Java/Hibernate.java.matches.json      : A
    101web/data/resources/Contributions/Java/hibernate-1-2-3.jar.matches.json : A
  files  : &fullmatches
    101web/data/resources/Contributions/C :
      exists : 0
    101web/data/resources/Contributions/CPlusPlus/main.cpp.matches.json :
      json : &cppmatches |
        [
          {"metadata" : {"geshi"    : "cpp"      }},
          {"metadata" : {"language" : "CPlusPlus"}}
        ]
    101web/data/resources/Contributions/CPlusPlus/Header.hpp.matches.json :
      json : *cppmatches
    101web/data/resources/Contributions/Java/Main.java.matches.json :
      json : &javamatches |
        [
          {"metadata" : {"geshi"     : "java"                                    }},
          {"metadata" : {"language"  : "Java"                                    }},
          {"metadata" : {"validator" : "technologies/JValidator/validator.py"    }},
          {"metadata" : {"extractor" : "technologies/JFactExtractor/extractor.py"}},
          {"metadata" : {"locator"   : "technologies/JFragmentLocator/locator.py"}}
        ]
    101web/data/resources/Contributions/Java/Hibernate.java.matches.json :
      json : *javamatches
    101web/data/resources/Contributions/Java/hibernate-1-2-3.jar.matches.json :
      json : |
        [
          {"metadata" : {"dependsOn" : "Hibernate"}}
        ]
    101web/data/dumps/matches.json :
      json : |
        {
          "failures" : {},
          "matches"  : [
            {
              "filename" : "Contributions/CPlusPlus/Header.hpp",
              "units"    : [
                {"metadata" : {"geshi"    : "cpp"      }},
                {"metadata" : {"language" : "CPlusPlus"}}
              ]
            },
            {
              "filename" : "Contributions/CPlusPlus/main.cpp",
              "units"    : [
                {"metadata" : {"geshi"    : "cpp"      }},
                {"metadata" : {"language" : "CPlusPlus"}}
              ]
            },
            {
              "filename" : "Contributions/Java/Hibernate.java",
              "units"    : [
                {"metadata" : {"geshi"     : "java"                                    }},
                {"metadata" : {"language"  : "Java"                                    }},
                {"metadata" : {"validator" : "technologies/JValidator/validator.py"    }},
                {"metadata" : {"extractor" : "technologies/JFactExtractor/extractor.py"}},
                {"metadata" : {"locator"   : "technologies/JFragmentLocator/locator.py"}}
              ]
            },
            {
              "filename" : "Contributions/Java/Main.java",
              "units"    : [
                {"metadata" : {"geshi"     : "java"                                    }},
                {"metadata" : {"language"  : "Java"                                    }},
                {"metadata" : {"validator" : "technologies/JValidator/validator.py"    }},
                {"metadata" : {"extractor" : "technologies/JFactExtractor/extractor.py"}},
                {"metadata" : {"locator"   : "technologies/JFragmentLocator/locator.py"}}
              ]
            },
            {
              "filename" : "Contributions/Java/hibernate-1-2-3.jar",
              "units"    : [
                {"metadata" : {"dependsOn" : "Hibernate"}}
              ]
            }
          ],
          "rules"    : [
            {
              "filename" : "Languages/CPlusPlus/.101meta",
              "rule"     : {
                "suffix"   : ".cpp",
                "metadata" : [
                  {"geshi"    : "cpp"      },
                  {"language" : "CPlusPlus"}
                ]
              }
            },
            {
              "filename" : "Languages/CPlusPlus/.101meta",
              "rule"     : {
                "suffix"   : ".hpp",
                "metadata" : [
                  {"geshi"    : "cpp"      },
                  {"language" : "CPlusPlus"}
                ]
              }
            },
            {
              "filename" : "Languages/Java/.101meta",
              "rule"     : {
                "suffix"   : ".java",
                "metadata" : [
                  {"geshi"     : "java"                                    },
                  {"language"  : "Java"                                    },
                  {"validator" : "technologies/JValidator/validator.py"    },
                  {"extractor" : "technologies/JFactExtractor/extractor.py"},
                  {"locator"   : "technologies/JFragmentLocator/locator.py"}
                ]
              }
            },
            {
              "filename" : "Technologies/Hibernate/.101meta",
              "rule"     : {
                "args"      : ["org.hibernate"],
                "suffix"    : ".java",
                "predicate" : "technologies/Java_platform/javaImport.py",
                "metadata"  : [
                  {"language"  : "Java"     },
                  {"dependsOn" : "Hibernate"}
                ]
              }
            },
            {
              "filename" : "Technologies/Hibernate/.101meta",
              "rule"     : {
                "basename" : "#^hibernate(.*)[.]jar$#",
                "metadata" : [
                  {"dependsOn" : "Hibernate"}
                ]
              }
            }
          ]
        }

# Another empty pull to ensure nothing changes that shouldn't.
4 :
  branch : matches101meta3
  diff   : {}
  files  : *fullmatches

# Some modifications to rules and files.
5 :
  indiff :
    101web/data/dumps/rules.json                                              : M
    101web/data/dumps/matches.json                                            : M
    101web/data/resources/Contributions/C/main.c.matches.json                 : A
    101web/data/resources/Contributions/C/Header.h.matches.json               : A
    101web/data/resources/Contributions/CPlusPlus/main.cpp.matches.json       : ~
    101web/data/resources/Contributions/CPlusPlus/Header.hpp.matches.json     : ~
    101web/data/resources/Contributions/Java/Main.java.matches.json           : ~
    101web/data/resources/Contributions/Java/Hibernate.java.matches.json      : ~
    101web/data/resources/Contributions/Java/hibernate-1-2-3.jar.matches.json : D
  files  : &modifiedmatches
    101web/data/resources/Contributions/Java/hibernate-1-2-3.jar.matches.json :
      exists : 0
    101web/data/resources/Contributions/C/main.c.matches.json :
      json : &cmatches |
        [
          {"metadata" : {"geshi"    : "c"}},
          {"metadata" : {"language" : "C"}}
        ]
    101web/data/resources/Contributions/C/Header.h.matches.json :
      json : *cmatches
    101web/data/resources/Contributions/CPlusPlus/main.cpp.matches.json :
      json : *cppmatches
    101web/data/resources/Contributions/CPlusPlus/Header.hpp.matches.json :
      json : *cppmatches
    101web/data/resources/Contributions/Java/Main.java.matches.json :
      json : *javamatches
    101web/data/resources/Contributions/Java/Hibernate.java.matches.json :
      json : *javamatches
    101web/data/dumps/matches.json :
      json : |
        {
          "failures" : {},
          "matches"  : [
            {
              "filename" : "Contributions/C/Header.h",
              "units"    : [
                {"metadata" : {"geshi"    : "c"}},
                {"metadata" : {"language" : "C"}}
              ]
            },
            {
              "filename" : "Contributions/C/main.c",
              "units"    : [
                {"metadata" : {"geshi"    : "c"}},
                {"metadata" : {"language" : "C"}}
              ]
            },
            {
              "filename" : "Contributions/CPlusPlus/Header.hpp",
              "units"    : [
                {"metadata" : {"geshi"    : "cpp"      }},
                {"metadata" : {"language" : "CPlusPlus"}}
              ]
            },
            {
              "filename" : "Contributions/CPlusPlus/main.cpp",
              "units"    : [
                {"metadata" : {"geshi"    : "cpp"      }},
                {"metadata" : {"language" : "CPlusPlus"}}
              ]
            },
            {
              "filename" : "Contributions/Java/Hibernate.java",
              "units"    : [
                {"metadata" : {"geshi"     : "java"                                    }},
                {"metadata" : {"language"  : "Java"                                    }},
                {"metadata" : {"validator" : "technologies/JValidator/validator.py"    }},
                {"metadata" : {"extractor" : "technologies/JFactExtractor/extractor.py"}},
                {"metadata" : {"locator"   : "technologies/JFragmentLocator/locator.py"}}
              ]
            },
            {
              "filename" : "Contributions/Java/Main.java",
              "units"    : [
                {"metadata" : {"geshi"     : "java"                                    }},
                {"metadata" : {"language"  : "Java"                                    }},
                {"metadata" : {"validator" : "technologies/JValidator/validator.py"    }},
                {"metadata" : {"extractor" : "technologies/JFactExtractor/extractor.py"}},
                {"metadata" : {"locator"   : "technologies/JFragmentLocator/locator.py"}}
              ]
            }
          ],
          "rules"    : [
            {
              "filename" : "Languages/C/.101meta",
              "rule"     : {
                "suffix"   : ".c",
                "metadata" : [
                  {"geshi"    : "c"},
                  {"language" : "C"}
                ]
              }
            },
            {
              "filename" : "Languages/C/.101meta",
              "rule"     : {
                "suffix"   : ".h",
                "metadata" : [
                  {"geshi"    : "c"},
                  {"language" : "C"}
                ]
              }
            },
            {
              "filename" : "Languages/CPlusPlus/.101meta",
              "rule"     : {
                "suffix"   : ".cpp",
                "metadata" : [
                  {"geshi"    : "cpp"      },
                  {"language" : "CPlusPlus"}
                ]
              }
            },
            {
              "filename" : "Languages/CPlusPlus/.101meta",
              "rule"     : {
                "suffix"   : ".hpp",
                "metadata" : [
                  {"geshi"    : "cpp"      },
                  {"language" : "CPlusPlus"}
                ]
              }
            },
            {
              "filename" : "Languages/Java/.101meta",
              "rule"     : {
                "suffix"   : ".java",
                "metadata" : [
                  {"geshi"     : "java"                                    },
                  {"language"  : "Java"                                    },
                  {"validator" : "technologies/JValidator/validator.py"    },
                  {"extractor" : "technologies/JFactExtractor/extractor.py"},
                  {"locator"   : "technologies/JFragmentLocator/locator.py"}
                ]
              }
            }
          ]
        }
