name    : rules101meta
tests   : 6
command : make -s test-rules101meta.debug

# Just an empty repo with no rules
1 :
  indiff :
    101web/data/dumps/rules.json : A
  files  : &emptyrules
    101web/data/dumps/rules.json :
      json : |
        {
            "numbers" : {
                "numberOfPredicates" : 0,
                "numberOfProblems"   : 0,
                "numberOfRules"      : 0,
                "numberOfSuffixes"   : 0
            },
            "problems" : {
                "invalidFiles"    : [],
                "unreadableFiles" : []
            },
            "results" : {
                "predicates" : {},
                "suffixes"   : [],
                "rules"      : []
            }
        }

# The empty repo again, making sure that there's no superfluous diff
2 :
  branch : rules101meta1
  diff   : {}
  files  : *emptyrules

# Proper test with .101meta files
3 :
  indiff :
    101web/data/dumps/rules.json : M
  files  : &fullrules
    101web/data/dumps/rules.json :
      json : |
        {
            "numbers"  : {
                "numberOfPredicates" : 1,
                "numberOfProblems"   : 1,
                "numberOfRules"      : 5,
                "numberOfSuffixes"   : 3
            },
            "problems" : {
                "invalidFiles"    : [],
                "unreadableFiles" : [
                    "Contributions/pythonSyb/.101meta"
                ]
            },
            "results"  : {
                "suffixes"   : [".cpp", ".hpp", ".java"],
                "predicates" : {
                    "technologies/Java_platform/javaImport.py" : [
                        "org.hibernate"
                    ]
                },
                "rules"      : [
                    {
                        "filename" : "Languages/CPlusPlus/.101meta",
                        "rule"     : {
                            "suffix"   : ".cpp",
                            "metadata" : [
                                {"geshi"    : "cpp"      },
                                {"language" : "CPlusPlus"}
                            ]
                        }
                    },
                    {
                        "filename" : "Languages/CPlusPlus/.101meta",
                        "rule"     : {
                            "suffix"   : ".hpp",
                            "metadata" : [
                                {"geshi"    : "cpp"      },
                                {"language" : "CPlusPlus"}
                            ]
                        }
                    },
                    {
                        "filename" : "Languages/Java/.101meta",
                        "rule"     : {
                            "suffix"   : ".java",
                            "metadata" : [
                                {"geshi"     : "java"                                    },
                                {"language"  : "Java"                                    },
                                {"validator" : "technologies/JValidator/validator.py"    },
                                {"extractor" : "technologies/JFactExtractor/extractor.py"},
                                {"locator"   : "technologies/JFragmentLocator/locator.py"}
                            ]
                        }
                    },
                    {
                        "filename" : "Technologies/Hibernate/.101meta",
                        "rule"     : {
                            "args"      : ["org.hibernate"],
                            "predicate" : "technologies/Java_platform/javaImport.py",
                            "suffix"    : ".java",
                            "metadata"  : [
                                {"language"  : "Java"     },
                                {"dependsOn" : "Hibernate"}
                            ]
                        }
                    },
                    {
                        "filename" : "Technologies/Hibernate/.101meta",
                        "rule"     : {
                            "basename" : "#^hibernate(.*)[.]jar$#",
                            "metadata" : [
                                {"dependsOn" : "Hibernate"}
                            ]
                        }
                    }
                ]
            }
        }

# Test with the same files again to make sure the file isn't generated again
4 :
  branch : rules101meta3
  diff   : {}
  files  : *fullrules

# After removing all rules but the failing one and fixing that to be valid JSON
5 :
  indiff :
    101repo/Contributions/pythonSyb/.101meta : M
    101web/data/dumps/rules.json             : M
  files  : &somerules
    101web/data/dumps/rules.json :
      json : |
        {
            "numbers"  : {
                "numberOfPredicates" : 0,
                "numberOfProblems"   : 0,
                "numberOfRules"      : 1,
                "numberOfSuffixes"   : 0
            },
            "problems" : {
                "invalidFiles"    : [],
                "unreadableFiles" : []
            },
            "results"  : {
                "suffixes"   : [],
                "predicates" : {},
                "rules"      : [
                    {
                        "filename" : "Contributions/pythonSyb/.101meta",
                        "rule"     : {
                            "basename" : "#^syb\\.py$#",
                            "metadata" : [
                                {"relevance" : "reuse"}
                            ]
                        }
                    }
                ]
            }
        }

# And again, just checking that nothing changes when it shouldn't
6 :
  branch : rules101meta5
  diff   : {}
  files  : *somerules
